using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Png;
using SixLabors.ImageSharp.Formats.Png.Chunks;

namespace MyNovelBuilder.WebApi.Helpers;

/// <summary>
/// Helper to write prompt metadata into PNG images.
/// </summary>
public static class PngPromptMetadataHelper
{
    private static readonly byte[] PngSignature = [137, 80, 78, 71, 13, 10, 26, 10];

    /// <summary>
    /// Adds prompt metadata to a PNG image, returning original bytes if metadata cannot be written.
    /// </summary>
    public static byte[] AddPromptMetadataIfPng(byte[] imageBytes, string prompt, ILogger? logger = null)
    {
        if (string.IsNullOrWhiteSpace(prompt) || !HasPngSignature(imageBytes))
        {
            return imageBytes;
        }

        try
        {
            using var image = Image.Load(imageBytes);
            var pngMetadata = image.Metadata.GetPngMetadata();
            pngMetadata.TextData.Add(new PngTextData("prompt", prompt, "en", "Prompt"));

            using var output = new MemoryStream();
            image.SaveAsPng(output, new PngEncoder
            {
                ChunkFilter = PngChunkFilter.None
            });
            return output.ToArray();
        }
        catch (UnknownImageFormatException ex)
        {
            logger?.LogWarning(ex, "Skipping prompt metadata injection because generated bytes are not a valid PNG image.");
            return imageBytes;
        }
        catch (Exception ex)
        {
            logger?.LogWarning(ex, "Failed to inject prompt metadata into PNG. Returning original image bytes.");
            return imageBytes;
        }
    }

    private static bool HasPngSignature(byte[] imageBytes)
    {
        if (imageBytes.Length < PngSignature.Length)
        {
            return false;
        }

        return imageBytes.AsSpan(0, PngSignature.Length).SequenceEqual(PngSignature);
    }
}
