<Project>
  <PropertyGroup>
    <VersionFile>$(MSBuildThisFileDirectory)..\..\..\VERSION</VersionFile>
    <Version>$([System.IO.File]::ReadAllText('$(VersionFile)').Trim())</Version>
    <PackageVersion>$(Version)</PackageVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(ElectronDesktopBuild)' == 'true'">
    <BaseIntermediateOutputPath>obj\electron\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
