using MyNovelBuilder.WebApi.Models.Chats;

namespace MyNovelBuilder.WebApi.Models.WorldBuilding;

/// <summary>
/// A persistent world-building agent session.
/// </summary>
public class WorldBuildingSession
{
    /// <summary>
    /// The session ID.
    /// </summary>
    public required Guid Id { get; init; }

    /// <summary>
    /// The time the session was created.
    /// </summary>
    public required DateTime CreatedAt { get; init; }

    /// <summary>
    /// The time the session was last updated.
    /// </summary>
    public required DateTime UpdatedAt { get; set; }

    /// <summary>
    /// The session name.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// Context selected for this session.
    /// </summary>
    public required WorldBuildingContext Context { get; init; }

    /// <summary>
    /// Messages in the world-building conversation.
    /// </summary>
    public IList<ChatMessage> Messages { get; set; } = [];

    /// <summary>
    /// Proposals generated by the agent.
    /// </summary>
    public IList<WorldBuildingProposal> Proposals { get; set; } = [];
}
