export enum PromptType {
  GenerateText = 'generateText',
  SummarizeText = 'summarizeText',
  ReplaceText = 'replaceText',
  CreateCompendiumRecord = 'createCompendiumRecord',
  EditCompendiumRecord = 'editCompendiumRecord',
  SendChatMessage = 'sendChatMessage',
  DescribeCompendiumImage = 'describeCompendiumImage',
  DescribeImage = 'describeImage',
  CreateCompendiumRecordImageGenerationPrompt = 'createCompendiumRecordImageGenerationPrompt',
  CreateStoryEvents = 'createStoryEvents',
  SuggestStoryDevelopments = 'suggestStoryDevelopments',
  TranslateNovel = 'translateNovel',
  PrepareImmersiveTts = 'prepareImmersiveTts',
  WorldBuildingAgent = 'worldBuildingAgent',
}
