export enum TtsProvider {
  Audio8 = 'audio8',
  Chatterbox = 'chatterbox',
  Custom = 'custom',
  DeApi = 'deApi',
  ElevenLabs = 'elevenLabs',
  Kokoro = 'kokoro',
  NanoGpt = 'nanoGpt',
  OpenRouter = 'openRouter',
  OmniVoice = 'omniVoice',
  PocketTts = 'pocketTts',
  Qwen3 = 'qwen3',
  UnrealSpeech = 'unrealSpeech',
  VibeVoice = 'vibeVoice',
}
